<?php
declare(strict_types=1);

/**
 * More of the names students here actually have, written out — read by
 * nepali_name_words() in devanagari.php alongside the list there, and taking
 * precedence over it where both hold a name.
 *
 * Why so many. Romanised Nepali writes the short अ and the long आ with the
 * same letter, and nothing in the spelling says which is meant: Rajan is
 * राजन, Rahul राहुल, Hamal हमाल, yet Kamal is कमल and Sagar सागर. No rule can
 * recover that, so a name only comes out right from its letters about half
 * the time — and a name is the one thing on a card that has to be right.
 * Written out here, it is.
 *
 * Keyed by the romanisation in lower case; several spellings of one name map
 * to the same Devanagari on purpose. Where a name has two accepted spellings
 * in Devanagari, the one in commoner use is given — a student who spells
 * theirs the other way types it into the Nepali-name box, which always wins.
 */
return [
    /* ---- surnames ---- */
    'ale' => 'आले',              'aale' => 'आले',             'bajgain' => 'बजगाईं',
    'baniya' => 'बानियाँ',         'baskota' => 'बास्कोटा',       'bastola' => 'बस्तोला',
    'belbase' => 'बेलबासे',        'bhetwal' => 'भेटवाल',         'bhujel' => 'भुजेल',
    'bishwokarma' => 'विश्वकर्मा',   'biswakarma' => 'विश्वकर्मा',     'bishowkarma' => 'विश्वकर्मा',
    'bk' => 'वि.क.',             'bogati' => 'बोगटी',           'bohora' => 'बोहोरा',
    'bomjan' => 'बोमजन',          'chalise' => 'चालिसे',          'chaulagain' => 'चौलागाईं',
    'dangol' => 'डंगोल',          'das' => 'दास',               'dawadi' => 'दवाडी',
    'dhimal' => 'धिमाल',          'dhital' => 'धिताल',           'dhungel' => 'ढुंगेल',
    'dulal' => 'दुलाल',           'gaire' => 'गैरे',             'gajurel' => 'गजुरेल',
    'ghalan' => 'घलान',           'ghising' => 'घिसिङ',          'gole' => 'गोले',
    'hamal' => 'हमाल',            'hayu' => 'हायु',              'humagain' => 'हुमागाईं',
    'jaisi' => 'जैसी',             'jha' => 'झा',                'jimba' => 'जिम्बा',
    'karn' => 'कर्ण',              'karna' => 'कर्ण',              'kattel' => 'कट्टेल',
    'katuwal' => 'कटुवाल',        'khatiwada' => 'खतिवडा',       'khatri' => 'खत्री',
    'kushwaha' => 'कुशवाहा',      'lamsal' => 'लम्साल',           'lopchan' => 'लोप्चन',
    'mahara' => 'महरा',           'mainali' => 'मैनाली',          'mainaly' => 'मैनाली',
    'mandal' => 'मण्डल',          'mishra' => 'मिश्र',             'moktan' => 'मोक्तान',
    'mokthan' => 'मोक्तान',        'mukhiya' => 'मुखिया',          'pahari' => 'पहरी',
    'pakhrin' => 'पाख्रिन',         'paswan' => 'पासवान',          'pathak' => 'पाठक',
    'paudyal' => 'पौड्याल',        'poudyal' => 'पौड्याल',         'prajapati' => 'प्रजापति',
    'rajbanshi' => 'राजवंशी',      'ranabhat' => 'रानाभाट',        'rawal' => 'रावल',
    'ray' => 'राय',               'rokaya' => 'रोकाया',          'rumba' => 'रुम्बा',
    'sada' => 'सदा',              'sigdel' => 'सिग्देल',          'sitaula' => 'सिटौला',
    'sunuwar' => 'सुनुवार',         'syangtan' => 'स्याङ्तान',       'thakuri' => 'ठकुरी',
    'thami' => 'थामी',             'thapaliya' => 'थपलिया',       'thing' => 'थिङ',
    'thokar' => 'थोकर',           'timsina' => 'तिम्सिना',         'titung' => 'तितुङ',
    'upadhyaya' => 'उपाध्याय',     'waiba' => 'वाइबा',            'yonjan' => 'योन्जन',
    'bhatt' => 'भट्ट',             'ghale' => 'घले',              'dong' => 'दोङ',
    'karki' => 'कार्की',           'lamichane' => 'लामिछाने',       'shrestha' => 'श्रेष्ठ',

    /* ---- middle names and the like ---- */
    'nath' => 'नाथ',              'mani' => 'मणि',               'dutta' => 'दत्त',
    'datta' => 'दत्त',             'kanta' => 'कान्त',             'kant' => 'कान्त',
    'bir' => 'वीर',               'shree' => 'श्री',              'shri' => 'श्री',

    /* ---- given names ---- */
    'abishek' => 'अभिषेक',        'amar' => 'अमर',              'amit' => 'अमित',
    'anish' => 'अनिश',            'ankit' => 'अंकित',            'anmol' => 'अनमोल',
    'arun' => 'अरुण',             'ashok' => 'अशोक',            'babu' => 'बाबु',
    'baburam' => 'बाबुराम',        'basanta' => 'बसन्त',          'bhupendra' => 'भूपेन्द्र',
    'bidur' => 'विदुर',            'bijay' => 'विजय',             'bijaya' => 'विजय',
    'vijay' => 'विजय',            'bimal' => 'विमल',             'binay' => 'विनय',
    'birendra' => 'वीरेन्द्र',       'bishnu' => 'विष्णु',            'bishwas' => 'विश्वास',
    'biswas' => 'विश्वास',          'chiranjibi' => 'चिरञ्जीवी',      'dambar' => 'डम्बर',
    'dev' => 'देव',               'dhan' => 'धन',               'dhiraj' => 'धीरज',
    'dil' => 'दिल',               'dipendra' => 'दिपेन्द्र',        'durga' => 'दुर्गा',
    'gagan' => 'गगन',             'gokul' => 'गोकुल',            'govinda' => 'गोविन्द',
    'gobinda' => 'गोविन्द',         'gyan' => 'ज्ञान',              'hem' => 'हेम',
    'hemraj' => 'हेमराज',          'himal' => 'हिमाल',            'hira' => 'हीरा',
    'ishwor' => 'ईश्वर',           'ishwar' => 'ईश्वर',            'ishan' => 'ईशान',
    'jagadish' => 'जगदीश',        'jay' => 'जय',                'jaya' => 'जय',
    'jitendra' => 'जितेन्द्र',       'kailash' => 'कैलाश',          'kamlesh' => 'कमलेश',
    'kapil' => 'कपिल',            'khem' => 'खेम',              'kishan' => 'किशन',
    'kishor' => 'किशोर',          'kundan' => 'कुन्दन',           'kushal' => 'कुशल',
    'lalit' => 'ललित',            'laxman' => 'लक्ष्मण',          'mahendra' => 'महेन्द्र',
    'manish' => 'मनिष',           'milan' => 'मिलन',            'mithun' => 'मिथुन',
    'mukesh' => 'मुकेश',           'mukunda' => 'मुकुन्द',          'narendra' => 'नरेन्द्र',
    'naresh' => 'नरेश',           'nawin' => 'नवीन',            'niraj' => 'नीरज',
    'nirajan' => 'निराजन',         'nischal' => 'निश्चल',          'nishan' => 'निशान',
    'nitesh' => 'नितेश',           'om' => 'ओम',                'pankaj' => 'पङ्कज',
    'pawan' => 'पवन',             'prabesh' => 'प्रवेश',           'prabhat' => 'प्रभात',
    'pradeep' => 'प्रदीप',          'pradip' => 'प्रदीप',            'prajwal' => 'प्रज्वल',
    'prashant' => 'प्रशान्त',        'prem' => 'प्रेम',              'rabi' => 'रवि',
    'rabin' => 'रविन',            'rahul' => 'राहुल',             'raja' => 'राजा',
    'rajan' => 'राजन',            'rajeev' => 'राजीव',           'rajiv' => 'राजीव',
    'rajkumar' => 'राजकुमार',       'ramchandra' => 'रामचन्द्र',      'ranjan' => 'रञ्जन',
    'ranjit' => 'रञ्जित',           'ratna' => 'रत्न',              'ritesh' => 'रितेश',
    'rohit' => 'रोहित',            'roshan' => 'रोशन',            'rupesh' => 'रुपेश',
    'sachin' => 'सचिन',           'sagun' => 'सगुन',             'sahil' => 'साहिल',
    'sameer' => 'समीर',           'sandesh' => 'सन्देश',          'sanjeev' => 'सञ्जीव',
    'sanjib' => 'सञ्जीव',          'sanjiv' => 'सञ्जीव',           'sarad' => 'शरद',
    'sharad' => 'शरद',            'saurav' => 'सौरभ',            'sourav' => 'सौरभ',
    'shankar' => 'शंकर',          'shekhar' => 'शेखर',           'shishir' => 'शिशिर',
    'shiv' => 'शिव',              'shreeram' => 'श्रीराम',         'sohan' => 'सोहन',
    'subash' => 'सुवास',           'subas' => 'सुवास',            'sudan' => 'सुदन',
    'sudeep' => 'सुदीप',           'sujit' => 'सुजित',            'sulav' => 'सुलभ',
    'suman' => 'सुमन',            'sumit' => 'सुमित',            'sunil' => 'सुनिल',
    'suresh' => 'सुरेश',           'sushil' => 'सुशील',           'tek' => 'टेक',
    'tilak' => 'तिलक',            'tulsi' => 'तुलसी',            'utsav' => 'उत्सव',
    'yam' => 'यम',                'yubaraj' => 'युवराज',          'yuvraj' => 'युवराज',
    'yuwaraj' => 'युवराज',         'chet' => 'चेत',               'mahesh' => 'महेश',

    'aakriti' => 'आकृति',         'akriti' => 'आकृति',           'aarati' => 'आरती',
    'arati' => 'आरती',            'aarju' => 'आर्जु',             'aarya' => 'आर्या',
    'aasha' => 'आशा',             'asha' => 'आशा',              'alina' => 'अलिना',
    'ambika' => 'अम्बिका',          'amrita' => 'अमृता',            'anamika' => 'अनामिका',
    'anisha' => 'अनिशा',           'anjana' => 'अञ्जना',           'ankita' => 'अंकिता',
    'anu' => 'अनु',               'apsara' => 'अप्सरा',           'archana' => 'अर्चना',
    'babita' => 'बबिता',           'bandana' => 'वन्दना',          'barsha' => 'वर्षा',
    'bhagawati' => 'भगवती',       'bhawana' => 'भावना',          'bhabana' => 'भावना',
    'bimala' => 'विमला',          'binita' => 'विनिता',          'bipana' => 'विपना',
    'chandani' => 'चाँदनी',         'chandrika' => 'चन्द्रिका',       'deepa' => 'दीपा',
    'dipa' => 'दीपा',              'deepika' => 'दीपिका',          'dipika' => 'दीपिका',
    'diksha' => 'दीक्षा',           'dikshya' => 'दीक्षा',           'drishti' => 'दृष्टि',
    'dristi' => 'दृष्टि',            'gauri' => 'गौरी',             'goma' => 'गोमा',
    'hema' => 'हेमा',              'indira' => 'इन्दिरा',           'isha' => 'ईशा',
    'jamuna' => 'जमुना',           'januka' => 'जनुका',           'jharana' => 'झरना',
    'junu' => 'जुनु',              'jyoti' => 'ज्योति',            'kabita' => 'कविता',
    'kavita' => 'कविता',           'kajal' => 'काजल',            'kalpana' => 'कल्पना',
    'kamala' => 'कमला',           'kamana' => 'कामना',          'kanchan' => 'कञ्चन',
    'karuna' => 'करुणा',           'khushi' => 'खुसी',            'kopila' => 'कोपिला',
    'kriti' => 'कृति',             'kritika' => 'कृतिका',          'kusum' => 'कुसुम',
    'lila' => 'लीला',              'mamata' => 'ममता',            'mamta' => 'ममता',
    'mandira' => 'मन्दिरा',         'manju' => 'मञ्जु',             'meena' => 'मीना',
    'mina' => 'मीना',              'menuka' => 'मेनुका',           'muna' => 'मुना',
    'nabina' => 'नविना',           'nirjala' => 'निर्जला',          'nirmala' => 'निर्मला',
    'nisha' => 'निशा',             'pabitra' => 'पवित्रा',          'parbati' => 'पार्वती',
    'parvati' => 'पार्वती',          'prabha' => 'प्रभा',            'prakriti' => 'प्रकृति',
    'pramila' => 'प्रमिला',          'pratibha' => 'प्रतिभा',         'prativa' => 'प्रतिभा',
    'pratima' => 'प्रतिमा',          'priyanka' => 'प्रियंका',         'purnima' => 'पूर्णिमा',
    'pushpa' => 'पुष्पा',            'puspa' => 'पुष्पा',             'rabina' => 'रविना',
    'rachana' => 'रचना',           'radha' => 'राधा',             'rama' => 'रमा',
    'ramita' => 'रमिता',           'ranjana' => 'रञ्जना',          'rekha' => 'रेखा',
    'renu' => 'रेनु',               'reshma' => 'रेश्मा',            'riya' => 'रिया',
    'rojina' => 'रोजिना',          'roshani' => 'रोशनी',          'roshni' => 'रोशनी',
    'rupa' => 'रूपा',              'sabita' => 'सविता',           'sabitri' => 'सावित्री',
    'sadikshya' => 'सदीक्षा',       'sajana' => 'सजना',           'salina' => 'सलिना',
    'samjhana' => 'सम्झना',         'samikshya' => 'समीक्षा',        'samiksha' => 'समीक्षा',
    'sangam' => 'सङ्गम',           'sanju' => 'सन्जु',              'sapana' => 'सपना',
    'sarala' => 'सरला',            'saraswati' => 'सरस्वती',        'shanta' => 'शान्ता',
    'shila' => 'शीला',             'shobha' => 'शोभा',            'shova' => 'शोभा',
    'sobha' => 'शोभा',             'shreya' => 'श्रेया',            'shrijana' => 'सृजना',
    'srijana' => 'सृजना',           'sirjana' => 'सिर्जना',          'shristi' => 'सृष्टि',
    'srishti' => 'सृष्टि',           'sristi' => 'सृष्टि',            'smriti' => 'स्मृति',
    'sneha' => 'स्नेहा',            'sonam' => 'सोनम',            'subhadra' => 'सुभद्रा',
    'sudha' => 'सुधा',              'sujata' => 'सुजाता',          'sumitra' => 'सुमित्रा',
    'sunaina' => 'सुनैना',           'sushila' => 'सुशीला',          'susmita' => 'सुस्मिता',
    'sushmita' => 'सुस्मिता',        'swastika' => 'स्वस्तिका',       'sweta' => 'श्वेता',
    'shweta' => 'श्वेता',            'tripti' => 'तृप्ति',             'trishna' => 'तृष्णा',
    'tulasa' => 'तुलसा',           'unnati' => 'उन्नति',           'urmila' => 'उर्मिला',
    'usha' => 'उषा',               'yamuna' => 'यमुना',           'yashoda' => 'यशोदा',
    'bharati' => 'भारती',          'hridaya' => 'हृदय',            'uday' => 'उदय',
    'udaya' => 'उदय',              'binaya' => 'विनय',            'vinay' => 'विनय',
    'sanjaya' => 'सञ्जय',           'vijaya' => 'विजय',            'abhaya' => 'अभय',
    'mritunjaya' => 'मृत्युञ्जय',     'mrityunjaya' => 'मृत्युञ्जय',    'prithvi' => 'पृथ्वी',
    'preeti' => 'प्रीति',            'priti' => 'प्रीति',             'kirti' => 'कीर्ति',
    'sukriti' => 'सुकृति',           'sanskriti' => 'संस्कृति',        'dhriti' => 'धृति',
    'mukti' => 'मुक्ति',             'bhakti' => 'भक्ति',             'shakti' => 'शक्ति',
    'kranti' => 'क्रान्ति',           'sriram' => 'श्रीराम',          'srikant' => 'श्रीकान्त',
    'srinivas' => 'श्रीनिवास',       'grishma' => 'ग्रीष्म',          'kanchha' => 'कान्छा',
    'tenzing' => 'तेन्जिङ',          'ngima' => 'ङिमा',             'pemba' => 'पेम्बा',
];
