<?php
if (!defined('VPL')) { http_response_code(403); exit; }
$VPL_EXPS = [
    'exp1' => 'Wavelength of light by Newton’s rings',
    'exp2' => 'Wavelength of light using a plane diffraction grating',
    'exp3' => 'Resolving power of a prism',
    'exp4' => 'Resolving power of a plane transmission grating',
    'exp5' => 'Refractive index of a prism for different wavelengths',
    'exp6' => 'Cauchy’s constants for the material of a prism',
    'exp7' => 'Specific rotation of sugar solution by Laurent’s half-shade polarimeter',
    'exp8' => 'Charge of an electron by Millikan’s oil-drop method',
    'exp9' => 'Specific charge of an electron (e/m) by the magnetron method',
    'exp10' => 'Specific charge of an electron (e/m) by Thomson’s method',
    'exp11' => 'Characteristics of a Geiger–Müller counter and its reliability',
    'exp12' => 'Linear absorption coefficient of β-particles using a G.M. counter',
    'exp13' => 'Resonant frequency and quality factor of a series LCR circuit',
    'exp14' => 'Study of the oscilloscope and its calibration for voltage and frequency',
    'exp15' => 'Unknown frequency of a source using Lissajous figures',
    'exp16' => 'Verification of the maximum power transfer theorem',
    'exp17' => 'Verification of Thevenin’s theorem and Norton’s theorem',
    'exp18' => 'Common-base (CB) characteristics of PNP and NPN transistors',
    'exp19' => 'Common-emitter (CE) characteristics of PNP and NPN transistors',
    'exp20' => 'Common-collector (CC) characteristics of PNP and NPN transistors',
    'exp21' => 'Characteristics of a regulated power supply using a Zener diode',
    'exp22' => 'Characteristics of a regulated power supply using an integrated circuit',
    'exp23' => 'Logic gates OR, AND and NOT using DTL and TTL',
    'exp24' => 'Logic gates NOR and NAND using DTL and TTL',
    'exp25' => 'Verification of NAND and NOR gates as universal gates',
];
